apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
  namespace: imdb
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: db-init
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-init
          image: imdb-api:latest
          imagePullPolicy: Never
          command: ["sh", "-c", "alembic upgrade head && python seed.py"]
          envFrom:
            - secretRef:
                name: db-secret
            - configMapRef:
                name: app-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
